name: docs
channels:
    - defaults
dependencies:
    - python=3.9.4
    - numpy=1.20.1
    - scipy=1.6.2
    - sphinx=1.8.5
    - sphinx_rtd_theme=0.4.3
    - pip=21.0.1
    - pip:
        - tanuna=0.1
        - sphinx_rtd_theme-0.4.3
