name: docs
channels:
    - defaults
dependencies:
    - python=3.9.4
    - numpy=1.20.1
    - scipy=1.6.2
    - sphinx=4.0.1
    - pip=21.0.1
    - pip:
        - sphinx_rtd_theme=0.5.2
        - tanuna=0.1
